[general]

import = [
    "~/.config/alacritty/themes/ayu_mirage.toml"
]

live_config_reload = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l"]}

[window]
padding = { x = 20, y = 20 }
decorations = "buttonless"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 13.5

offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Never" }
thickness = 0.5
